"""
NBA Over/Under Predictor - Column Legend

This module contains comprehensive descriptions for all columns used in the
prediction system. The LEGEND dictionary maps column names to human-readable
descriptions for documentation and Excel exports.
"""

LEGEND = {
    "GAME_ID": "Unique string identifier for the game, ensuring each row ties to a specific matchup on a certain date. Useful for merging data and tracking games distinctly.",
    "SEASON_TYPE": "Indicates if the game is Regular Season, Playoffs, etc., helping differentiate context such as intensity and roster usage.",
    "GAME_DATE": "Date the game took place (or will take place). Useful for chronological analyses and computing rolling stats up to that point.",
    "TEAM_NAME_TEAM_HOME": "Full name of the home team (e.g., Los Angeles Lakers). Useful to identify who is hosting and analyze home-court trends.",
    "GAME_NUMBER_TEAM_HOME": "Chronological count of this home team’s games in that season type (e.g., 1 for the first, 82 for the last regular-season game). Helps assess how far along they are in the schedule.",
    "TEAM_NAME_TEAM_AWAY": "Full name of the away (visiting) team. Useful to identify who is traveling and analyze away-game trends.",
    "GAME_NUMBER_TEAM_AWAY": "Chronological count of the away team’s games in that season type. Helps show how many games they’ve played prior to this matchup.",
    "MATCHUP": "Textual descriptor of the matchup (e.g., Lakers vs. Celtics). Useful for quick reference to both teams and their home/away roles.",
    "PREDICTED_TOTAL_SCORE": "If present, a model’s projected combined final score for this game. Useful for forecasting points outcomes.",
    "TEAM_ID_TEAM_HOME": "NBA’s internal ID for the home team as a string. Useful for merging and referencing specific franchises.",
    "TEAM_CITY_TEAM_HOME": "Home team’s city (e.g., Los Angeles). Helps with location-based insights or clarifying a team’s geographic home.",
    "TEAM_ABBREVIATION_TEAM_HOME": "Short tag for the home team (e.g., LAL). Useful for concise labeling and quick cross-referencing in data and visualizations.",
    "TEAM_ID_TEAM_AWAY": "NBA’s internal ID for the away team as a string. Useful for merges and referencing franchises in queries.",
    "TEAM_CITY_TEAM_AWAY": "Away team’s city (e.g., Boston). Aids geographic or travel analyses.",
    "TEAM_ABBREVIATION_TEAM_AWAY": "Short tag for the away team (e.g., BOS). Useful for concise labeling and references.",
    "MATCHUP_TEAM_AWAY": "Alternate textual form of the matchup from the away perspective (e.g., BOS @ LAL). Helpful for clarifying which side is traveling.",
    "SEASON_ID": "Internal NBA season ID (e.g., '22022' or '42022'). Useful for grouping or filtering data by specific NBA season.",
    "IS_PLAYOFF_GAME": "Binary flag (0 or 1) showing whether the game is in the Playoffs. Important because playoff intensity and rotations differ from regular season.",
    "PLAYOFF_GAMES_LAST_SEASON_TEAM_AWAY": "Count of playoff games the away team played in the previous season. Useful to gauge their recent postseason experience.",
    "PLAYOFF_GAMES_LAST_SEASON_TEAM_HOME": "Count of playoff games the home team played in the previous season. Also measures prior postseason experience.",
    "SEASON_YEAR": "Four-digit integer representing the year of the season (e.g., 2023). Simplifies filtering data compared to the full SEASON_ID.",
    "WINS_BEFORE_THIS_GAME_TEAM_HOME": "Total wins the home team accumulated prior to this matchup. Indicates how successful they’ve been up to now.",
    "LOSSES_BEFORE_THIS_GAME_TEAM_HOME": "Total losses the home team had prior to this matchup. Combined with wins to describe their record so far.",
    "TEAM_RECORD_BEFORE_GAME_TEAM_HOME": "Home team’s pre-game win percentage (wins / (wins + losses)). Shows how strong they have been so far.",
    "REST_DAYS_BEFORE_MATCH_TEAM_HOME": "Number of days since the home team’s previous game. Useful in assessing fatigue, particularly on short rest.",
    "PTS_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Average points scored by the home team over their last 5 games (regardless of venue). Reflects recent offensive form.",
    "PTS_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "Average points over the last 5 games played in the same home/away status. If they’re home now, it’s the last 5 home games. Useful for venue-specific scoring trends.",
    "PTS_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date average points by the home team, excluding this game. Serves as a baseline for their usual scoring output.",
    "PTS_LAST_10_WMA_BEFORE_TEAM_HOME": "Weighted moving average of the home team’s points over their last 10 games. Assigns more weight to recent performances for improved trend tracking.",
    "PTS_LAST_HOME_AWAY_10_WMA_BEFORE_TEAM_HOME": "If the home team is currently at home, it’s the weighted moving average of their last 10 home games (or away if they’re currently away). Highlights recent venue-specific scoring.",
    "OFF_RATING_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Offensive Rating (points/100 possessions) for the home team across their last 5 games. Shows recent offensive efficiency.",
    "OFF_RATING_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "Offensive Rating in the last 5 games at the same home/away context. Reveals venue-specific offensive efficiency.",
    "OFF_RATING_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date Offensive Rating for the home team, excluding this game. Serves as a consistent measure of offensive quality over the season.",
    "DEF_RATING_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Defensive Rating (points allowed per 100 possessions) for the home team’s last 5 games. Gauges recent defensive effectiveness.",
    "DEF_RATING_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "Defensive Rating over the last 5 home/away games. Helps isolate performance tied to specific venues.",
    "DEF_RATING_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date Defensive Rating for the home team, excluding this game. Baseline measure of their defense.",
    "NET_RATING_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Net Rating (OffRtg – DefRtg) for the home team’s last 5 games. Summarizes recent overall performance.",
    "NET_RATING_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "Net Rating specifically in the last 5 games at the same home/away status. Useful if the team performs differently on the road vs. at home.",
    "NET_RATING_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date Net Rating for the home team, excluding the current game. Indicates overall performance across the season.",
    "EFG_PCT_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Effective Field Goal Percentage in the home team’s last 5 games. Accounts for the extra value of three-pointers.",
    "EFG_PCT_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "Home team’s eFG% in the last 5 home or away games (depending on current venue). Highlights shooting efficiency influenced by location.",
    "EFG_PCT_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date eFG% for the home team, excluding this game. Reflects overall shooting efficiency so far.",
    "PACE_PER40_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Average pace (possessions per 40 minutes) in the home team’s last 5 games. Higher pace typically means more possessions and scoring.",
    "PACE_PER40_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "Pace over the home team’s last 5 games in the same home/away context. Some teams push tempo more at home.",
    "PACE_PER40_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date pace (per 40 minutes) for the home team, excluding this game. Baseline for how quickly they play overall.",
    "FG3A_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Average 3-point attempts by the home team in their last 5 games. Shows how reliant they are on the 3-point shot recently.",
    "FG3A_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "3-point attempts over the last 5 games in the same home/away context. Venue can affect shooting confidence or style.",
    "FG3A_SEASON_BEFORE_AVG_TEAM_HOME": "Home team’s season-to-date average 3-point attempts, excluding the current game. Represents how often they typically shoot threes.",
    "FG3M_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Average 3-point makes in the home team’s last 5 games. Reflects recent success behind the arc.",
    "FG3M_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "3-point makes in the last 5 games at the same home/away context, capturing venue-specific 3-point performance.",
    "FG3M_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date average of 3-point makes for the home team, excluding this game. Baseline for their typical 3-point scoring.",
    "FGM_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Average total field goals made by the home team in the last 5 games. Measures broad scoring from the field.",
    "FGM_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "Field goals made in the last 5 home or away games for the home team, providing location-based scoring trends.",
    "FGM_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date average of field goals made (excluding the current game). Baseline for how many shots they convert each night.",
    "FGA_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Average field goal attempts by the home team in their last 5 games. Indicates recent shot volume.",
    "FGA_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "Field goal attempts in the last 5 same-venue games for the home team. Helps see if they shoot more at home vs. away.",
    "FGA_SEASON_BEFORE_AVG_TEAM_HOME": "Home team’s average field goal attempts over the season to date, excluding this game. Shows typical shooting frequency.",
    "FG_PCT_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Overall field goal percentage for the home team in their last 5 games. Highlights recent shooting effectiveness.",
    "FG_PCT_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "Field goal percentage over the last 5 same-venue games for the home team. Useful for seeing if venue impacts FG%.",
    "FG_PCT_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date field goal percentage for the home team, excluding this game. Baseline shooting accuracy.",
    "FG3_PCT_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "3-point shooting percentage for the home team’s last 5 games. Shows recent accuracy from deep.",
    "FG3_PCT_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "3-point percentage in the last 5 games at the same home/away context, illustrating how venue might affect 3-point accuracy.",
    "FG3_PCT_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date 3-point percentage for the home team, excluding this game. Baseline for how well they shoot from distance.",
    "FTA_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Average free throw attempts by the home team in their last 5 games. Indicates how often they draw shooting fouls recently.",
    "FTA_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "FT attempts in the last 5 home/away games, helpful for seeing if the team draws more fouls at home or away.",
    "FTA_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date free throw attempts for the home team, excluding the current game. Baseline for how frequently they get to the line.",
    "FTM_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Average free throws made by the home team in the last 5 games. Reflects recent scoring from the line.",
    "FTM_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "Free throws made in the last 5 games at home or away. Helps analyze if officiating or aggression changes by venue.",
    "FTM_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date free throws made for the home team, excluding the current game. Shows typical points gained at the line.",
    "TS_PCT_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "True Shooting Percentage in the home team’s last 5 games, accounting for FG, 3PT, and FT efficiency. Reflects overall scoring efficiency recently.",
    "TS_PCT_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "True Shooting % in the last 5 games at the same venue for the home team. Indicates location-based scoring efficiency.",
    "TS_PCT_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date True Shooting Percentage for the home team, excluding the current game. Baseline for overall shooting/FT efficiency.",
    "POSS_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Average number of possessions used by the home team in their last 5 games. More possessions typically boost scoring potential.",
    "POSS_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "Home team’s average possessions in their last 5 same-venue games. Shows how tempo might differ by location.",
    "POSS_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date possessions for the home team, excluding this game. Baseline for typical pace of play.",
    "PIE_LAST_ALL_5_MATCHES_BEFORE_TEAM_HOME": "Player Impact Estimate aggregated to the team level for the last 5 games, indicating their share of game events. Reflects recent dominance or performance contribution.",
    "PIE_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_HOME": "Team PIE for the last 5 same-venue games, indicating if the team performs better or worse based on location.",
    "PIE_SEASON_BEFORE_AVG_TEAM_HOME": "Season-to-date team PIE, excluding this game. Baseline for how the team influences outcomes overall.",
    "WINS_BEFORE_THIS_GAME_TEAM_AWAY": "Total wins the away team had before this matchup. Indicates their success up to this point.",
    "LOSSES_BEFORE_THIS_GAME_TEAM_AWAY": "Total losses for the away team prior to this matchup. Useful to combine with wins to see their record.",
    "TEAM_RECORD_BEFORE_GAME_TEAM_AWAY": "Away team’s pre-game win percentage (wins / (wins + losses)). Summarizes their performance so far.",
    "REST_DAYS_BEFORE_MATCH_TEAM_AWAY": "Days of rest the away team had since their last game. Reflects potential fatigue levels.",
    "PTS_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Away team’s average points over their last 5 games (regardless of venue). Shows recent offensive production.",
    "PTS_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "If the away team is currently away, it’s the average points of their last 5 away games. Venue-specific scoring form.",
    "PTS_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date average points scored by the away team, excluding this game. Baseline for typical offensive output.",
    "PTS_LAST_10_WMA_BEFORE_TEAM_AWAY": "Weighted moving average of the away team’s points over their last 10 games. Gives more weight to recent games for a better short-term trend.",
    "PTS_LAST_HOME_AWAY_10_WMA_BEFORE_TEAM_AWAY": "For the away team currently on the road, a weighted moving average of their last 10 away games. Captures venue-specific short-term scoring trends.",
    "OFF_RATING_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Offensive Rating for the away team in their last 5 games. Reflects recent offensive efficiency.",
    "OFF_RATING_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "Offensive Rating in the last 5 away games (if away now). Useful for measuring venue-based offensive performance.",
    "OFF_RATING_SEASON_BEFORE_AVG_TEAM_AWAY": "Away team’s season-to-date Offensive Rating, excluding this game. Baseline for how efficiently they score overall.",
    "DEF_RATING_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Defensive Rating (points allowed per 100 possessions) for the away team’s last 5 games. Shows recent defensive performance.",
    "DEF_RATING_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "Defensive Rating in the last 5 games matching the current venue status for the away team. Helps see if they defend differently on the road.",
    "DEF_RATING_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date Defensive Rating for the away team, excluding this game. Baseline measure of defensive strength.",
    "NET_RATING_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Net Rating for the away team in their last 5 games (OffRtg – DefRtg). Indicates overall recent success.",
    "NET_RATING_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "Net Rating specifically for the away team’s last 5 away games if they’re on the road. Shows venue-specific net performance.",
    "NET_RATING_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date Net Rating for the away team, excluding the current game. Overall measure of their offense minus defense.",
    "EFG_PCT_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Effective Field Goal % in the away team’s last 5 games. Reflects recent shooting efficiency.",
    "EFG_PCT_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "Effective FG% in the last 5 away games if the away team is currently away. Shows location-based shooting success.",
    "EFG_PCT_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date eFG% for the away team, excluding the current game. Baseline for how well they shoot overall.",
    "PACE_PER40_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Average possessions per 40 minutes in the away team’s last 5 games. Indicates recent game tempo.",
    "PACE_PER40_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "Pace specifically for the away team’s last 5 games at the same venue context. Highlights if they play faster/slower away from home.",
    "PACE_PER40_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date pace for the away team, excluding the current game. Baseline for how quickly they play overall.",
    "FG3A_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "3-point attempts averaged by the away team in their last 5 games. Tracks recent reliance on threes.",
    "FG3A_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "3-point attempts in the last 5 road games if the away team is currently away. Useful for seeing if they shoot differently away from home.",
    "FG3A_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date 3-point attempts for the away team, excluding this game. Baseline for typical 3-point shot volume.",
    "FG3M_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Average 3-pointers made in the away team’s last 5 games. Shows recent success from beyond the arc.",
    "FG3M_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "3-pointers made in the last 5 games matching the current away context. Checks if they make more or fewer threes on the road.",
    "FG3M_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date 3-pointers made by the away team, excluding the current game. Baseline 3PT scoring figure.",
    "FGM_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Average field goals made by the away team in their last 5 games, reflecting broad shooting success.",
    "FGM_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "Field goals made in the last 5 away games. Useful for analyzing if the team’s shot-making changes on the road.",
    "FGM_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date field goals made by the away team, excluding this game. Baseline for typical shot conversions.",
    "FGA_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Average field goal attempts by the away team in their last 5 games. Indicates recent shot volume.",
    "FGA_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "Field goal attempts in the last 5 away games for the away team. Helps evaluate volume differences between home and road.",
    "FGA_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date field goal attempts for the away team, excluding the current game. Baseline measure of typical shooting frequency.",
    "FG_PCT_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Field goal percentage in the away team’s last 5 games. Shows recent shooting accuracy.",
    "FG_PCT_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "FG% in the last 5 away games if currently away. Reflects venue-related shooting performance.",
    "FG_PCT_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date field goal percentage for the away team, excluding this game. Baseline measure of overall shooting success.",
    "FG3_PCT_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "3-point percentage for the away team’s last 5 games. Shows recent accuracy from beyond the arc.",
    "FG3_PCT_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "3PT% in the last 5 away games for the away team if they’re currently away. Illustrates location-based 3PT accuracy.",
    "FG3_PCT_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date 3-point percentage for the away team, excluding the current game. Baseline for their typical long-range shooting.",
    "FTA_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Average free throw attempts for the away team over the last 5 games. Indicates how often they draw fouls recently.",
    "FTA_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "Free throw attempts in the last 5 games matching the current away venue. Useful for venue-based aggression trends.",
    "FTA_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date free throw attempts for the away team, excluding this game. Baseline for how frequently they get to the line.",
    "FTM_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Average free throws made by the away team in their last 5 games, showing recent scoring from the charity stripe.",
    "FTM_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "FT made in the last 5 away games if the away team is currently away. Helps see if location influences free throw performance.",
    "FTM_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date free throws made by the away team, excluding this game. Baseline for their typical points off free throws.",
    "TS_PCT_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "True Shooting % in the away team’s last 5 games, giving an overall snapshot of recent scoring efficiency.",
    "TS_PCT_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "TS% for the last 5 away games, if the away team is currently on the road. Venue-based efficiency insight.",
    "TS_PCT_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date TS% for the away team, excluding the current game. Baseline measure of combined FG and FT efficiency.",
    "POSS_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Average possessions in the away team’s last 5 games. Reflects how quickly they’re playing recently.",
    "POSS_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "Away team’s average possessions in their last 5 away games. Useful to see if they change tempo on the road.",
    "POSS_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date possessions for the away team, excluding this game. Baseline for how fast they typically play.",
    "PIE_LAST_ALL_5_MATCHES_BEFORE_TEAM_AWAY": "Team-level Player Impact Estimate in the away team’s last 5 games, measuring overall share of game events.",
    "PIE_LAST_HOME_AWAY_5_MATCHES_BEFORE_TEAM_AWAY": "PIE in the last 5 away games if the away team is currently traveling. Helps reveal venue-driven performance differences.",
    "PIE_SEASON_BEFORE_AVG_TEAM_AWAY": "Season-to-date team PIE for the away team, excluding the current matchup. Baseline for their overall impact level.",
    "AVG_POINTS_CONCEDED_AT_HOME_BEFORE_GAME": "For the home team, average points allowed when playing at home so far this season, excluding this game. Indicates how well they typically defend their own court.",
    "AVG_POINTS_CONCEDED_AWAY_BEFORE_GAME": "For the away team, average points allowed when playing on the road, excluding the current game. Shows their typical road defense.",
    "DIFERENCE_POINTS_CONCEDED_VS_EXPECTED_BEFORE_HOME_GAME": "Difference between the away team’s usual scoring average and what the home team typically concedes at home. Helps gauge if the away offense exceeds or falls short of the home defense norm.",
    "DIFERENCE_POINTS_CONCEDED_VS_EXPECTED_BEFORE_AWAY_GAME": "Difference between the home team’s usual scoring average and the away team’s typical points allowed on the road. Highlights if the home offense outperforms or underperforms against away defense norms.",
    "AVG_DIFFERENCE_CONCEDED_VS_ANNOTATED_BEFORE_GAME_TEAM_HOME": "Rolling average of how the home team’s defensive performance (points conceded) compares to some expected value, over previous home games. Reveals if they consistently allow more or fewer points than expected.",
    "AVG_DIFFERENCE_CONCEDED_VS_ANNOTATED_BEFORE_GAME_TEAM_AWAY": "Same type of rolling average but for the away team’s defense vs. expectation. Indicates if they consistently outperform or underperform on the road.",
    "LAST_1_GAMES_TOTAL_POINTS_BEFORE": "Total combined points (both teams) from their most recent head-to-head matchup (before this game). Useful for analyzing direct H2H trends.",
    "LAST_2_GAMES_TOTAL_POINTS_BEFORE": "Combined points from the second-most-recent head-to-head matchup. Helps track multiple prior confrontations.",
    "LAST_3_GAMES_TOTAL_POINTS_BEFORE": "Combined points from the third-most-recent head-to-head. Continues building an H2H scoring trend.",
    "LAST_4_GAMES_TOTAL_POINTS_BEFORE": "Combined points from the fourth-most-recent head-to-head. Part of the broader H2H scoring pattern.",
    "LAST_5_GAMES_TOTAL_POINTS_BEFORE": "Combined points from the fifth-most-recent head-to-head. Final piece in the short historical matchup record.",
    "LAST_5_GAMES_TOTAL_POINTS_BEFORE_MEAN": "Average total points over the last 5 head-to-head matchups. Captures typical combined scoring in direct encounters.",
    "PTS_TEAM_HOME_TREND_SLOPE_LAST_5_GAMES_BEFORE": "Slope from a linear regression on the home team’s points in their last 5 games, indicating if scoring is trending up or down.",
    "PTS_TEAM_AWAY_TREND_SLOPE_LAST_5_GAMES_BEFORE": "Slope for the away team’s scoring over their last 5 games, revealing if they’re heating up or cooling off offensively.",
    "PTS_COMBINED_TREND_SLOPE_LAST_5_GAMES_BEFORE": "Sum of the home and away slope values, showing overall upward or downward trend in both teams’ combined scoring.",
    "TS_PCT_TEAM_HOME_TREND_SLOPE_LAST_5_GAMES_BEFORE": "Trend line slope of the home team’s True Shooting Percentage in the last 5 games, highlighting improvements or declines in shooting efficiency.",
    "TS_PCT_TEAM_AWAY_TREND_SLOPE_LAST_5_GAMES_BEFORE": "Away team’s True Shooting % slope over the last 5 games, indicating improving or worsening overall shot efficiency.",
    "TS_PCT_COMBINED_TREND_SLOPE_LAST_5_GAMES_BEFORE": "Sum of both teams’ TS% slopes, giving a combined view of how efficient scoring is trending for both sides.",
    "TOTAL_PTS_SEASON_BEFORE_AVG": "Sum of home and away teams’ season-to-date average points. Serves as a quick baseline for combined scoring potential.",
    "TOTAL_PTS_LAST_GAMES_AVG": "Sum of each team’s last 5 (or last 10 WMA) average points, reflecting recent combined scoring form.",
    "BACK_TO_BACK": "Boolean indicating if both teams played only 1 day ago. Highlights potential fatigue or lower efficiency from consecutive games.",
    "DIFERENCE_HOME_OFF_AWAY_DEF_BEFORE_MATCH": "Home team’s recent Offensive Rating minus the away team’s recent Defensive Rating, showing if the home offense might have an advantage.",
    "DIFERENCE_AWAY_OFF_HOME_DEF_BEFORE_MATCH": "Away team’s recent Offensive Rating minus the home team’s recent Defensive Rating, indicating if the away offense might have an edge.",
}
